name: crypto_chart_view
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # DI
  get_it: ^7.2.0
  injectable: ^1.5.3
  provider: ^6.0.2
  # DB
  sqflite: ^2.0.2
  # Web API
  dio: ^4.0.4
  retrofit: ^3.0.1+1
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  web_socket_channel: ^2.1.0
  # min-code helpers
  equatable: ^2.0.3
  json_annotation: ^4.4.0
  # UI
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  # logic
  connectivity_plus: ^2.2.1
  intl: ^0.17.0
  path_provider: ^2.0.9
  rxdart: ^0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  injectable_generator: ^1.5.3
  json_serializable: ^6.1.4
  retrofit_generator: ^4.0.1


flutter:
  uses-material-design: true
